openapi: 3.0.0
info:
  title: URL Shortener (docs minimal)
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api-v1/:
    get:
      summary: Get number of links (placeholder)
      responses:
        '200':
          description: OK
